using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Europa.Soulbreakers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Europa.Soulbreakers.UI;

[GenerateTypedNameReferences]
public sealed partial class SoulbreakerTeleportationConsoleWindow : FancyWindow
{
    public event Action? OneModeButtonPressed;
    public event Action? AllModeButtonPressed;
    public event Action? ExecuteTeleportButtonPressed;
    public event Action<NetEntity>? OnSelectedTarget;

    public SoulbreakerTeleportationConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartButton.OnPressed += _ => ExecuteTeleportButtonPressed?.Invoke();

        OneModeButton.OnPressed += _ => OneModeButtonPressed?.Invoke();
        AllModeButton.OnPressed += _ => AllModeButtonPressed?.Invoke();
    }

    public void UpdateState(SoulbreakerTeleportationConsoleUiState state)
    {
        CrewList.Children.Clear();
        foreach (var (ent, name) in state.Targets)
        {
            var btn = new Button
            {
                Text = name.Length != 0 ? name : "Неизвестно",
                HorizontalExpand = true,
                Pressed = state.Selected == ent,
                ToggleMode = true,
                MinSize = new Vector2(20, 20)
            };

            btn.OnPressed += _ => OnSelectedTarget?.Invoke(ent);

            CrewList.AddChild(btn);
        }

        OneModeButton.Pressed = !state.TeleportAll;
        AllModeButton.Pressed = state.TeleportAll;
    }
}
